appName: bloc-test
developer: chris
email: hitchcott@gmail.com
appURL: test.hitchcott.com
repo: ''
apiURL: 'http://strato-dev2.blockapps.net'
transferGasLimit: '21000'
contractGasLimit: '10000000'
gasPrice: '50000000000'
